[tool.poetry]
name = "yoga-bot"
version = "0.1.0"
description = "bot for selling yoga private chats"
authors = ["Your Name <you@example.com>"]
license = "none"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.1.0"
sqlalchemy = "^2.0.21"
aiosqlite = "^0.19.0"
apscheduler = "^3.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
