"""migrations

Revision ID: 40f88b67dc61
Revises: 75db0d124cfc
Create Date: 2024-10-14 19:52:08.197603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f88b67dc61'
down_revision: Union[str, None] = '75db0d124cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_limits_rate_id'), 'model_limits', ['rate_id'], unique=False)
    op.drop_column('rate', 'daily_limit_chats')
    op.drop_column('rate', 'daily_limit_images')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate', sa.Column('daily_limit_images', sa.INTEGER(), nullable=True))
    op.add_column('rate', sa.Column('daily_limit_chats', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_model_limits_rate_id'), table_name='model_limits')
    op.drop_table('model_limits')
    # ### end Alembic commands ###
