"""migrations


Revision ID: 48501a106eaa
Revises: dd42516533e8
Create Date: 2024-10-26 16:06:51.517011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48501a106eaa'
down_revision: Union[str, None] = 'dd42516533e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('midjourney_prompts', sa.Column('type_', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('midjourney_prompts', 'type_')
    # ### end Alembic commands ###
