"""migrations

Revision ID: 8301ed12ee9c
Revises: 40f88b67dc61
Create Date: 2024-10-14 23:26:28.664578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8301ed12ee9c'
down_revision: Union[str, None] = '40f88b67dc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counts_of_requests', sa.Column('model', sa.Enum(), nullable=True))
    op.drop_column('counts_of_requests', 'type_of_request')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counts_of_requests', sa.Column('type_of_request', sa.VARCHAR(length=5), nullable=True))
    op.drop_column('counts_of_requests', 'model')
    # ### end Alembic commands ###
