"""migrations

Revision ID: 9927ed1859f7
Revises: cc16e6e10476
Create Date: 2024-10-27 02:05:02.720656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9927ed1859f7'
down_revision: Union[str, None] = 'cc16e6e10476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate', sa.Column('midjourney_generations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate', 'midjourney_generations')
    # ### end Alembic commands ###
