"""migrations

Revision ID: ca474f00c5f6
Revises: a6bbfd55fb11
Create Date: 2024-10-11 19:34:46.856067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca474f00c5f6'
down_revision: Union[str, None] = 'a6bbfd55fb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counts_of_requests', sa.Column('type_of_request', sa.Enum('CHAT', 'IMAGE', name='typeofrequestenum'), nullable=True))
    op.drop_column('counts_of_requests', 'model')
    op.add_column('rate', sa.Column('daily_limit_chats', sa.Integer(), nullable=True))
    op.add_column('rate', sa.Column('daily_limit_images', sa.Integer(), nullable=True))
    op.drop_column('rate', 'daily_limit_dalle')
    op.drop_column('rate', 'daily_limit_gpt')
    op.add_column('users', sa.Column('chat_model', sa.Enum('GPT_4O', 'GPT_4O_MINI', name='chatmodelenum'), nullable=True))
    op.add_column('users', sa.Column('image_model', sa.Enum('DALL_E_3', 'DALL_E_2', name='imagemodelenum'), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_model')
    op.drop_column('users', 'chat_model')
    op.add_column('rate', sa.Column('daily_limit_gpt', sa.INTEGER(), nullable=True))
    op.add_column('rate', sa.Column('daily_limit_dalle', sa.INTEGER(), nullable=True))
    op.drop_column('rate', 'daily_limit_images')
    op.drop_column('rate', 'daily_limit_chats')
    op.add_column('counts_of_requests', sa.Column('model', sa.VARCHAR(), nullable=True))
    op.drop_column('counts_of_requests', 'type_of_request')
    # ### end Alembic commands ###
