"""migrations

Revision ID: d16d47d677a0
Revises: 48501a106eaa
Create Date: 2024-10-26 22:16:34.924384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16d47d677a0'
down_revision: Union[str, None] = '48501a106eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('midjourney_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('count_of_generations', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('remaining_midjourney_generations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remaining_midjourney_generations')
    op.drop_table('midjourney_prices')
    # ### end Alembic commands ###
