"""migrations

Revision ID: e0c1e52b6927
Revises: ae212f04587d
Create Date: 2024-10-15 16:46:05.076567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c1e52b6927'
down_revision: Union[str, None] = 'ae212f04587d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate', sa.Column('price_3', sa.Integer(), nullable=True))
    op.add_column('rate', sa.Column('price_6', sa.Integer(), nullable=True))
    op.add_column('rate', sa.Column('price_12', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate', 'price_12')
    op.drop_column('rate', 'price_6')
    op.drop_column('rate', 'price_3')
    # ### end Alembic commands ###
